name: ci
on:
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches:
      - main
env:
  BATON_LOG_LEVEL: debug
  BATON_TOKEN: "${{ secrets.BATON_TOKEN }}"
  BATON_ORGANIZATION_ID: "${{ secrets.BATON_ORGANIZATION_ID }}"
jobs:
  test-spaces:
    runs-on: ubuntu-latest
    env:
      CONNECTOR_GRANT: "${{ vars.TEST_SPACES_GRANT }}"
      CONNECTOR_ENTITLEMENT: "${{ vars.TEST_SPACES_ENTITLEMENT }}"
      CONNECTOR_PRINCIPAL: "${{ vars.TEST_SPACES_PRINCIPAL }}"
      CONNECTOR_PRINCIPAL_TYPE: "${{ vars.TEST_PRINCIPAL_TYPE || 'user' }}"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Build baton-contentful
        run: go build ./cmd/baton-contentful
      - name: Run baton-contentful
        run: ./baton-contentful
      - name: Install baton
        uses: ConductorOne/github-workflows/actions/get-baton@v2
      - name: Test grant and revoke
        uses: ConductorOne/github-workflows/actions/sync-test@v2
        with:
          connector: ./baton-contentful
          baton-entitlement: "${{ env.CONNECTOR_ENTITLEMENT }}"
          baton-principal: "${{ env.CONNECTOR_PRINCIPAL }}"
          baton-principal-type: "${{ env.CONNECTOR_PRINCIPAL_TYPE }}"
  test-teams:
    runs-on: ubuntu-latest
    env:
      CONNECTOR_GRANT: "${{ vars.TEST_TEAMS_GRANT }}"
      CONNECTOR_ENTITLEMENT: "${{ vars.TEST_TEAMS_ENTITLEMENT }}"
      CONNECTOR_PRINCIPAL: "${{ vars.TEST_TEAMS_PRINCIPAL }}"
      CONNECTOR_PRINCIPAL_TYPE: "${{ vars.TEST_PRINCIPAL_TYPE || 'user' }}"
    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.x
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build baton-contentful
        run: go build ./cmd/baton-contentful
      - name: Run baton-contentful
        run: ./baton-contentful
      - name: Install baton
        uses: ConductorOne/github-workflows/actions/get-baton@v2
      - name: Test grant and revoke
        uses: ConductorOne/github-workflows/actions/sync-test@v2
        with:
          connector: ./baton-contentful
          baton-entitlement: "${{ env.CONNECTOR_ENTITLEMENT }}"
          baton-principal: "${{ env.CONNECTOR_PRINCIPAL }}"
          baton-principal-type: "${{ env.CONNECTOR_PRINCIPAL_TYPE }}"
